name: docker creation

# Run on PR requests. And on main itself.
on:
  push:
    branches:
      - main
  pull_request:


# A workflow run is made up of one or more jobs that can run sequentially or
# in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can
      # access it
      # docker login --username ${{ github.actor }} --password ${{ secrets.CR_PAT }} ghcr.io
      # - name: Build and push docker image
      # run: |
      #   echo $CR_PAT | docker login ghcr.io -u thangqd --password-stdin
      #   docker tag geoprocessing_web ghcr.io/thangqd/geoprocessing:latest
      #   docker push ghcr.io/thangqd/geoprocessing:latest

      - uses: actions/checkout@v3

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: 'Build and push docker image'
        run: |
          docker build . --tag ghcr.io/thangqd/geoprocessing:latest
          docker push ghcr.io/thangqd/geoprocessing:latest